---
# tasks for deploy_jenkins_role
- name: Add Jenkins repo key to the system
  apt_key:
      url: "{{ jenkins.url_repo_key }}"
      state: present

- name: Add Jenkins repo to sources List
  apt_repository:
            repo: "{{ jenkins.url_repo }}"
            state: present

- name: Update repos
  apt: update_cache=yes

- name: Install Jenkins
  apt: name=jenkins state=present

- name: Enshure the Jenkins is running
  service: name=jenkins state=started enabled=yes
